DROP DATABASE IF EXISTS weather_app;

CREATE DATABASE weather_app;

CREATE TABLE Locations (
  id VARCHAR(255) NOT NULL PRIMARY KEY,
  location VARCHAR(255) NOT NULL,
  history JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
